# Generated by Django 3.2.15 on 2022-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCreationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, max_length=5120, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
