# Generated by Django 3.2.15 on 2022-08-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name_plural': 'Catrgories',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.FileField(upload_to='Files/')),
                ('tech_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.category')),
            ],
        ),
    ]
