# Generated by Django 3.2.15 on 2022-08-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('Last_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='forms')),
            ],
        ),
    ]
